tesla_admin/blueprints/__init__.py
#  TeSLA Admin
#  Copyright (C) 2019 Universitat Oberta de Catalunya
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
#
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

tesla_admin/blueprints/data/__init__.py
#  TeSLA Admin
#  Copyright (C) 2019 Universitat Oberta de Catalunya
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
#
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

tesla_admin/blueprints/informed_consent/__init__.py
#  TeSLA Admin
#  Copyright (C) 2019 Universitat Oberta de Catalunya
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
#
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

tesla_admin/blueprints/report/__init__.py
#  TeSLA Admin
#  Copyright (C) 2019 Universitat Oberta de Catalunya
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
#
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

tesla_admin/blueprints/report/routes.py
#  TeSLA Admin
#  Copyright (C) 2019 Universitat Oberta de Catalunya
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
#
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

from flask import Blueprint, jsonify, url_for, render_template, request, send_from_directory
from tesla_admin.decorators import certificate_required
from tesla_admin import logger, tesla_db, tesla_data_provider, app
from tesla_admin.helpers import api_response
from tesla_admin.errors import TESLA_API_STATUS_CODE
from tesla_models.database.utils import decode_data, ResultsPagination
import tesla_models.schemas as schemas
from tesla_models import tep_db
from datetime import datetime, timedelta
import time
import base64
from flask_security import roles_required, login_required
from flask_sqlalchemy import Pagination
#from xhtml2pdf import pisa
import io
import os
import math
import simplejson
from tesla_admin.instrument_api import InstrumentAPI


reports = Blueprint('reports', __name__, template_folder='templates', static_folder='static')

def create_pdf(pdf_data):
    pdf = io.BytesIO()

    with open(os.path.join(reports.static_folder, 'css', 'reports.css'), 'r') as f:
        report_css = f.read()
#    pisa.CreatePDF(io.StringIO(pdf_data), dest=pdf)
    return pdf


@reports.route('/', methods=['GET'])
@login_required
@roles_required('Statistics')
def reports_index():

    pdf = create_pdf(render_template('reports/sample.html'))
    pdf_b64 = base64.b64encode(pdf.getvalue()).decode()

    return render_template('report_list.html', page = 'reports.list', pdf_b64=pdf_b64)


def _get_learner_instrument_stats(learner_result, context_statistics):

    learner_stats = {}
    learner_stats['instruments'] = {}
    auth_levels = []
    content_levels = []
    security_levels = []
    for instrument_id in context_statistics.keys():
        # Initialize the instrument statistics
        level = 0.0
        prob_learner = 0.0
        prob_context = 0.0
        h_prob_learner = 1.0
        h_prob_context = 1.0
        confidence = 0.0
        histogram = []
        result_bean = None

        # TODO: Put polarity in instrument fields
        instrument_polarity = 1
        if instrument_id in [6]:
            instrument_polarity = -1

        # TODO: Put properties in instrument fields
        if instrument_id in [1, 3, 5]:
            is_auth = True
            is_content = False
            is_security = False
        elif instrument_id in [7]:
            is_auth = True
            is_content = True
            is_security = False
        elif instrument_id in [2, 3]:
            is_auth = False
            is_content = False
            is_security = True
        elif instrument_id in [6]:
            is_auth = False
            is_content = True
            is_security = False
        else:
            is_auth = False
            is_content = False
            is_security = False

        # If learner have data for this instrument, update the statistics
        if instrument_id in learner_result['instruments']:
            context_hist = context_statistics[instrument_id]['histogram']
            histogram = tesla_db.statistics.get_learner_instrument_valid_results_histogram(learner_result['tesla_id'],
                                                                                       instrument_id)

            confidence = learner_result['instruments'][instrument_id]['valid'] / (learner_result['instruments'][instrument_id]['valid'] + learner_result['instruments'][instrument_id]['failed'] + 0.00000001)

            if confidence < 0.5:
                level = 2
            else:
                # Compute a final level
                if learner_result['instruments'][instrument_id]['average'] < 1.0:
                    result_bean = math.floor(learner_result['instruments'][instrument_id]['average']*10.0)
                else:
                    result_bean = 9

                if result_bean == 0:
                    prob_learner = (histogram[result_bean] + 0.5 * histogram[result_bean + 1]) / (sum(histogram) + 0.00000001)
                    prob_context = (context_hist[result_bean] + 0.5 * context_hist[result_bean + 1]) / (sum(context_hist) + 0.00000001)
                    if instrument_polarity > 0:
                        h_prob_learner = sum(histogram[1:10]) / (sum(histogram) + 0.00000001)
                        h_prob_context = sum(context_hist[1:10]) / (sum(context_hist) + 0.00000001)
                    else:
                        h_prob_learner = 0.0
                        h_prob_context = 0.0
                elif result_bean == 9:
                    prob_learner = (histogram[result_bean] + 0.5 * histogram[result_bean - 1]) / (sum(histogram) + 0.00000001)
                    prob_context = (context_hist[result_bean] + 0.5 * context_hist[result_bean - 1]) / (sum(context_hist) + 0.00000001)
                    if instrument_polarity > 0:
                        h_prob_learner = 0.0
                        h_prob_context = 0.0
                    else:
                        h_prob_learner = sum(histogram[0:9]) / (sum(histogram) + 0.00000001)
                        h_prob_context = sum(context_hist[0:9]) / (sum(context_hist) + 0.00000001)

                else:
                    prob_learner = (0.5 * histogram[result_bean - 1] + histogram[result_bean] + 0.5 * histogram[result_bean + 1]) / (sum(histogram) + 0.00000001)
                    prob_context = (0.5 * context_hist[result_bean - 1] + context_hist[result_bean] + 0.5 * context_hist[result_bean + 1]) / (sum(context_hist) + 0.00000001)
                    if instrument_polarity > 0:
                        h_prob_learner = sum(histogram[result_bean + 1:10]) / (sum(histogram) + 0.00000001)
                        h_prob_context = sum(context_hist[result_bean+1:10]) / (sum(context_hist) + 0.00000001)
                    else:
                        h_prob_learner = sum(histogram[0:result_bean]) / (sum(histogram) + 0.00000001)
                        h_prob_context = sum(context_hist[0:result_bean]) / (sum(context_hist) + 0.00000001)

                # Get instrument thresholds
                thresholds = context_statistics[instrument_id]['thresholds']

                # Build final recomendation
                if thresholds is not None:
                    if (instrument_polarity > 0 and learner_result['instruments'][instrument_id]['average'] > thresholds.medium) or \
                            (instrument_polarity < 0 and (1.0 - learner_result['instruments'][instrument_id]['average']) > thresholds.medium):
                        # If the mean value is in the green side, assume that is the learner
                        level = 3
                    else:
                        # Compare with the context
                        if h_prob_learner > 0.75:
                            # If the obtained value is not usual at all for this learner, assume that is not the learner
                            level = 1
                        elif h_prob_context < 0.5:
                            # If the value is larger than the contextual value, put in warning
                            level = 2
                        else:
                            # Otherwise put in danger
                            level = 1
                else:
                    # Compare with the context
                    if h_prob_learner < 0.4 and h_prob_context < 0.4:
                        level = 3
                    elif h_prob_learner > 0.75:
                        # If the obtained value is not usual at all for this learner, assume that is not the learner
                        level = 1
                    elif h_prob_context < 0.5:
                        # If the value is larger than the contextual value, put in warning
                        level = 2
                    else:
                        # Otherwise put in danger
                        level = 1

        # Store the instrument statistics
        learner_stats['instruments'][instrument_id] = {
            'prob_learner': prob_learner,
            'prob_context': prob_context,
            'h_prob_learner': h_prob_learner,
            'h_prob_context': h_prob_context,
            'confidence': confidence,
            'level': level,
            'instrument_polarity': instrument_polarity,
            'histogram': histogram,
            'result_bean': result_bean,
            'thresholds': context_statistics[instrument_id]['thresholds']
        }

        # Store the level
        if is_auth:
            auth_levels.append(level)
        if is_content:
            content_levels.append(level)
        if is_security:
            security_levels.append(level)

    # Compute a final levels
    if len(auth_levels) > 0:
        positive = 3 in auth_levels
        negative = 1 in auth_levels

        if positive and negative:
            auth_level = 2
        elif not positive and negative:
            auth_level = 1
        elif positive and not negative:
            auth_level = 3
        else:
            auth_level = math.floor(sum(auth_levels) / len(auth_levels))
    else:
        auth_level = 0

    if len(content_levels) > 0:
        positive = 3 in content_levels
        negative = 1 in content_levels

        if positive and negative:
            content_level = 2
        elif not positive and negative:
            content_level = 1

tesla_admin/blueprints/send/__init__.py
#  TeSLA Admin
#  Copyright (C) 2019 Universitat Oberta de Catalunya
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
#
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

tesla_admin/blueprints/send/routes.py
#  TeSLA Admin
#  Copyright (C) 2019 Universitat Oberta de Catalunya
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
#
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

from flask import Blueprint, jsonify, url_for, render_template, request
from tesla_admin.decorators import certificate_required
from tesla_admin import logger, tesla_db, tesla_data_provider
from tesla_admin.helpers import api_response
from tesla_admin.errors import TESLA_API_STATUS_CODE
from .forms import CategoryForm
from tesla_models.database.utils import decode_data
from flask_security import roles_required, login_required

send = Blueprint('send', __name__, template_folder='templates', static_folder='static')

@send.route('/learners', methods=['GET'])
@login_required
@roles_required('Admin')
def learners():
    form = CategoryForm()

    categories = tesla_db.learners.get_send_categories()

    return render_template('learners.html', page = 'send.learners', form=form, categories=categories)


@send.route('/learner/categories/<string:tesla_id>', methods=["GET"])
@login_required
@roles_required('Admin')
def get_learner_categories(tesla_id):

    categories = tesla_db.learners.get_send_user(tesla_id)

    instruments = set()
    options = set()
    cat = []
    for c in categories:
        data = decode_data(c.data)
        c.data = data
        instruments.update(data['instruments'])
        options.update(data['options'])
        cat.append(c.id)

    return api_response(TESLA_API_STATUS_CODE.SUCCESS, {"categories": cat, "instruments": list(instruments), "options": list(options)})


@send.route('/learner/categories/<string:tesla_id>', methods=["POST"])
@login_required
@roles_required('Admin')
def set_learner_categories(tesla_id):

    # Update assigned categories
    new_cats = request.get_json()

    if new_cats is not None:
        tesla_db.learners.update_learner_send_categories(tesla_id, new_cats['categories'])

    return get_learner_categories(tesla_id)


@send.route('/categories', methods=['GET', 'POST'])
@login_required
@roles_required('Admin')
def categories():
    form = CategoryForm()

    has_errors = True
    if form.validate_on_submit():
        data = {'options': form.data.get('options'), 'instruments': [int(i) for i in form.data.get('instruments')]}
        if form.data["id"] < 0:
            tesla_db.learners.create_send_category(description=form.data.get('description'), data=data)
        else:
            tesla_db.learners.update_send_category(id=form.data.get('id'), description=form.data.get('description'), data=data)
        has_errors = False

    if request.method == "GET":
        has_errors = False

    categories = tesla_db.learners.get_send_categories()

    return render_template('categories.html', page='send.categories', form=form, categories=categories, has_errors=has_errors)


@send.route('/category/<int:id>', methods=['GET'])
@login_required
@roles_required('Admin')
def get_category_data(id):
    category = tesla_db.learners.get_send_category(id)
    if category is None:
        api_response(TESLA_API_STATUS_CODE.REQUEST_NOT_FOUND, http_code=404)
    data = decode_data(category.data)

    return api_response(TESLA_API_STATUS_CODE.SUCCESS, {'id': category.id, 'description': category.description,
                                                        'data': data})

tesla_admin/templates/_macros.html
{% macro render_pagination(pagination, endpoint, id, view) %}
<!--
  ~ TeSLA Admin
  ~ Copyright (C) 2019 Universitat Oberta de Catalunya
  ~
  ~ This program is free software: you can redistribute it and/or modify
  ~ it under the terms of the GNU Affero General Public License as published by
  ~ the Free Software Foundation, either version 3 of the License, or
  ~ (at your option) any later version.
  ~
  ~ This program is distributed in the hope that it will be useful,
  ~ but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  ~ GNU Affero General Public License for more details.
  ~
  ~ You should have received a copy of the GNU Affero General Public License
  ~ along with this program.  If not, see <http://www.gnu.org/licenses/>.
  -->

<nav aria-label="pagination">
    <ul class="pagination">
        <li class="page-item{% if not pagination.has_prev %} disabled{% endif %}">
            <a class="page-link" href="{{ url_for(endpoint, page=pagination.prev_num, id=id, view=view) }}" aria-label="{{_ ('Previous') }}">
                <i class="fa fa-arrow-left" aria-hidden="true"></i>
                <span class="sr-only">{{_ ('Previous') }}</span>
            </a>
        </li>
        {% for p in pagination.iter_pages %}
            {% if p %}
                {% if p != pagination.page %}
                    <li class="page-item">
                        <a class="page-link" href="{{ url_for(endpoint, page=p, id=id, view=view) }}" aria-label="{{ p }}">{{ p }}</a>
                    </li>
                {% else %}
                    <li class="page-item active">
                        <a class="page-link" href="{{ url_for(endpoint, page=p, id=id, view=view) }}">{{ p }}</a>
                    </li>
                {% endif %}
            {% else %}
                <li class="page-item disabled">
                    <span class="ellipsis">&hellip;</span>
                </li>
            {% endif %}
        {% endfor %}
        <li class="page-item{% if not pagination.has_next %} disabled{% endif %}">
            <a class="page-link" href="{{ url_for(endpoint, page=pagination.next_num, id=id, view=view) }}" aria-label="{{_ ('Next') }}">
                <i class="fa fa-arrow-right" aria-hidden="true"></i>
                <span class="sr-only">{{_ ('Next') }}</span>
            </a>
        </li>
    </ul>
</nav>
{% endmacro %}

tesla_admin/templates/footer.html
<!--
  ~ TeSLA Admin
  ~ Copyright (C) 2019 Universitat Oberta de Catalunya
  ~
  ~ This program is free software: you can redistribute it and/or modify
  ~ it under the terms of the GNU Affero General Public License as published by
  ~ the Free Software Foundation, either version 3 of the License, or
  ~ (at your option) any later version.
  ~
  ~ This program is distributed in the hope that it will be useful,
  ~ but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  ~ GNU Affero General Public License for more details.
  ~
  ~ You should have received a copy of the GNU Affero General Public License
  ~ along with this program.  If not, see <http://www.gnu.org/licenses/>.
  -->

<footer class="main-footer">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-6">
                <p>TeSLA &copy; 2017-2019</p>
            </div>
        </div>
    </div>
</footer>

tesla_admin/templates/home.html
{% extends "layout.html" %}
{% block sections %}

{% endblock %}
{% block body_scripts %}
    <!--
  ~ TeSLA Admin
  ~ Copyright (C) 2019 Universitat Oberta de Catalunya
  ~
  ~ This program is free software: you can redistribute it and/or modify
  ~ it under the terms of the GNU Affero General Public License as published by
  ~ the Free Software Foundation, either version 3 of the License, or
  ~ (at your option) any later version.
  ~
  ~ This program is distributed in the hope that it will be useful,
  ~ but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  ~ GNU Affero General Public License for more details.
  ~
  ~ You should have received a copy of the GNU Affero General Public License
  ~ along with this program.  If not, see <http://www.gnu.org/licenses/>.
  -->

<script src="{{ url_for('static', filename='js/home-premium.js') }}"></script>
{% endblock %}

tesla_admin/templates/navigation_side.html
<!--
  ~ TeSLA Admin
  ~ Copyright (C) 2019 Universitat Oberta de Catalunya
  ~
  ~ This program is free software: you can redistribute it and/or modify
  ~ it under the terms of the GNU Affero General Public License as published by
  ~ the Free Software Foundation, either version 3 of the License, or
  ~ (at your option) any later version.
  ~
  ~ This program is distributed in the hope that it will be useful,
  ~ but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  ~ GNU Affero General Public License for more details.
  ~
  ~ You should have received a copy of the GNU Affero General Public License
  ~ along with this program.  If not, see <http://www.gnu.org/licenses/>.
  -->

<nav class="side-navbar">
    <!-- Sidebar Header-->
    <!--<div class="sidebar-header d-flex align-items-center">
        {% if current_user.is_authenticated %}
            <div class="avatar">
                <img src="img/avatar-1.jpg" alt="..." class="img-fluid rounded-circle">
            </div>
            <div class="title">
                <h1 class="h4">Mark Stephen</h1>
                <p>Web Designer</p>
            </div>
        {% endif %}
    </div>-->

    <!-- Sidebar Navidation Menus-->
    <ul class="list-unstyled">
        <li {% if not page or page=="home" %}class="active"{% endif %}>
            <a href="{{ url_for('home') }}"> <i class="fa fa-home"></i>{{ _('Home') }} </a>
        </li>
        {% if current_user.has_role('Admin') %}
            <li {% if page.startswith("users") %}class="active"{% endif %}>
                <a href="{{ url_for('users.index') }}"> <i class="fa fa-users"></i>{{ _('User Management') }} </a>
            </li>
        {% endif %}
        {% if current_user.has_role('Admin') %}
            <li {% if page.startswith("send") %}class="active"{% endif %}>
                <a href="#sendDropdown" aria-expanded="{% if page.startswith("send") %}true{% else %}false{% endif %}" data-toggle="collapse"> <i class="fab fa-accessible-icon"></i>{{ _('SEND') }} </a>
                <ul id="sendDropdown" class="collapse list-unstyled {% if page.startswith("send") %}show{% endif %}">
                    <li {% if page=="send.learners" %}class="active"{% endif %}>
                        <a href="{{ url_for('send.learners') }}">{{ _('Learners') }}</a>
                    </li>
                    <li {% if page=="send.categories" %}class="active"{% endif %}>
                        <a href="{{ url_for('send.categories') }}">{{ _('Categories') }}</a>
                    </li>
                </ul>
            </li>
        {% endif %}
        {% if current_user.has_role('Admin') %}
            <li {% if page.startswith("informed_consent") %}class="active"{% endif %}>
                <a href="{{ url_for('informed_consent.index') }}"> <i class="fab fa-leanpub"></i>{{ _('Informed consent') }} </a>
            </li>

        {% endif %}
        {% if current_user.has_role('Admin') %}
            <li {% if page.startswith("data") %}class="active"{% endif %}>
                <a href="#dataDropdown" aria-expanded="{% if page.startswith("data") %}true{% else %}false{% endif %}" data-toggle="collapse"> <i class="fa fa-database"></i>{{ _('Data') }} </a>
                <ul id="dataDropdown" class="collapse list-unstyled {% if page.startswith("data") %}show{% endif %}">
                    <li {% if page=="data.learner" %}class="active"{% endif %}>
                        <a href="{{ url_for('data.learner') }}">{{ _('Learner') }}</a>
                    </li>
                    <li {% if page=="data.activity" %}class="active"{% endif %}>
                        <a href="{{ url_for('data.activity') }}">{{ _('Activity') }}</a>
                    </li>
                    <li {% if page=="data.course" %}class="active"{% endif %}>
                        <a href="{{ url_for('data.course') }}">{{ _('Course') }}</a>
                    </li>
                </ul>
            </li>
        {% endif %}
        {% if current_user.has_role('Admin') %}
            <li {% if page.startswith("system") %}class="active"{% endif %}>
                <a href="#systemDropdown" aria-expanded="{% if page.startswith("system") %}true{% else %}false{% endif %}" data-toggle="collapse"> <i class="fa fa-cog"></i>{{ _('System') }} </a>
                <ul id="systemDropdown" class="collapse list-unstyled {% if page.startswith("system") %}show{% endif %}">
                    <li {% if page=="system.monitoring" %}class="active"{% endif %}>
                        <a href="{{ url_for('system.monitoring') }}">{{ _('Monitoring') }}</a>
                    </li>
                    <li {% if page=="system.configuration" %}class="active"{% endif %}>
                        <a href="{{ url_for('system.configuration') }}">{{ _('Configuration') }}</a>
                    </li>
                    <li {% if page=="system.vle" %}class="active"{% endif %}>
                        <a href="{{ url_for('system.vle') }}">{{ _('VLE') }}</a>
                    </li>
                </ul>
            </li>
        {% endif %}
        {% if current_user.has_role('Statistics') %}
            <li {% if page.startswith("stats") %}class="active"{% endif %}>
                <a href="#statsDropdown" aria-expanded="{% if page.startswith("stats") %}true{% else %}false{% endif %}" data-toggle="collapse"> <i class="fa fa-chart-line"></i>{{ _('Statistics') }} </a>
                <ul id="statsDropdown" class="collapse list-unstyled {% if page.startswith("stats") %}show{% endif %}">
                    <li {% if page=="stats.rt" %}class="active"{% endif %}>
                        <a href="{{ url_for('stats.rt') }}">{{ _('Real Time') }}</a>
                    </li>
                    <li {% if page=="stats.learners" %}class="active"{% endif %}>
                        <a href="{{ url_for('stats.learners_stats') }}">{{ _('Learners') }}</a>
                    </li>
                    <li {% if page=="stats.activities" %}class="active"{% endif %}>
                        <a href="{{ url_for('stats.activities') }}">{{ _('Activities') }}</a>
                    </li>
                    <li {% if page=="stats.courses" %}class="active"{% endif %}>
                        <a href="{{ url_for('stats.courses') }}">{{ _('Courses') }}</a>
                    </li>
                </ul>
            </li>
        {% endif %}
        {% if current_user.has_role('Reporting') %}
            <li {% if page.startswith("reports") %}class="active"{% endif %}>
                <a href="#reportsDropdown" aria-expanded="{% if page.startswith("reports") %}true{% else %}false{% endif %}" data-toggle="collapse"> <i class="fa fa-file-alt"></i>{{ _('Reports') }} </a>
                <ul id="reportsDropdown" class="collapse list-unstyled {% if page.startswith("reports") %}show{% endif %}">
                    <li {% if page=="reports.list" %}class="active"{% endif %}>
                        <a href="{{ url_for('reports.reports_index') }}">{{ _('List') }}</a>
                    </li>
                </ul>
            </li>
        {% endif %}
    </ul>
</nav>

tesla_admin/templates/report_footer.html
<!--
  ~ TeSLA Admin
  ~ Copyright (C) 2019 Universitat Oberta de Catalunya
  ~
  ~ This program is free software: you can redistribute it and/or modify
  ~ it under the terms of the GNU Affero General Public License as published by
  ~ the Free Software Foundation, either version 3 of the License, or
  ~ (at your option) any later version.
  ~
  ~ This program is distributed in the hope that it will be useful,
  ~ but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  ~ GNU Affero General Public License for more details.
  ~
  ~ You should have received a copy of the GNU Affero General Public License
  ~ along with this program.  If not, see <http://www.gnu.org/licenses/>.
  -->

<footer class="main-footer">
    <div class="eu-funded">
        <img src="{{ url_for('static', filename='img/TeSLA_EU_flag.svg') }}"/>
        <br />
        <span>FUNDED BY THE EUROPEAN UNION</span>
    </div>
    <span>TeSLA is not responsible for any contents linked or referred to from these pages. It does not associate or identify itself with the content of third parties to which it refers via a link. Furthermore TESLA is not liable for any postings or messages published by users of discussion boards, guest books or mailing lists provided on its page. We have no control over the nature, content and availability of any links that may appear on our site. The inclusion of any links does not necessarily imply a recommendation or endorse the views expressed within them.
        <br/>TeSLA is coordinated by Universitat Oberta de Catalunya (UOC) and funded by the European Commission’s Horizon 2020 ICT Programme. This website reflects the views only of the authors, and the Commission cannot be held responsible for any use which may be made of the information contained therein.
    </span>
</footer>