tesla_admin/blueprints/users/forms.py
#  TeSLA Admin
#  Copyright (C) 2019 Universitat Oberta de Catalunya
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
#
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

from flask_wtf import FlaskForm
from flask_babel import gettext
from wtforms import StringField, BooleanField, SubmitField, SelectMultipleField, HiddenField, IntegerField, widgets, PasswordField, validators
from wtforms.validators import DataRequired
from tesla_admin import tesla_db
from wtforms.ext.sqlalchemy.fields import QuerySelectMultipleField, QuerySelectField
from tesla_models.models import Role

def get_roles():
    return lambda: Role.query.all()

def get_id(element):
    if type(element) is Role:
        return str(element.id)

    return str(element)

class UserForm(FlaskForm):
    roles_data = [(str(i.id), i.name) for i in tesla_db.users.get_roles()]

    username = StringField(gettext('Username'), validators=[DataRequired()], render_kw={"placeholder": gettext('Username')})
    email = StringField(gettext('Email'), validators=[DataRequired()], render_kw={"placeholder": gettext('Email')})
    active = BooleanField(gettext('Active'))
    roles = SelectMultipleField(gettext('Roles'), choices=roles_data, coerce=get_id)
    password = PasswordField(gettext('Password'), validators=[validators.EqualTo('repeat_password')])
    repeat_password = PasswordField(gettext('Repeat password'))

tesla_admin/blueprints/users/__init__.py
#  TeSLA Admin
#  Copyright (C) 2019 Universitat Oberta de Catalunya
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
#
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

tesla_admin/blueprints/users/routes.py
#  TeSLA Admin
#  Copyright (C) 2019 Universitat Oberta de Catalunya
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
#
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

from flask import Blueprint, jsonify, url_for, render_template, request, redirect, flash
from flask_security import roles_required, login_required
from tesla_admin import tesla_db, get_locale
from tesla_models import models
from tesla_admin.blueprints.users.forms import UserForm

users = Blueprint('users', __name__, template_folder='templates', static_folder='static')


@users.route('/', methods=['GET'])
@login_required
@roles_required('Admin')
def index():
    user_count = tesla_db.users.get_user_count()

    return render_template('index.html', page = 'users.index', user_count=user_count)


@users.route('/list_ajax', methods=['GET'])
@login_required
@roles_required('Admin')
def list_ajax():
    q = None
    limit = None
    offset = None

    q = request.args.get('search')
    limit = request.args.get('limit')
    offset = request.args.get('offset')
    sort = request.args.get('sort')
    order = request.args.get('order')

    list_users = tesla_db.users.get_users(q=q, limit=limit, offset=offset, order=order, sort=sort)
    total_users = tesla_db.users.count_users(q=q)

    users_data = models.users_schema.dump(list_users)

    return_data = {}
    return_data['total'] = total_users
    return_data['rows'] = users_data[0]

    return jsonify(return_data), 200


@users.route('/user_delete', methods=['GET'])
@login_required
@roles_required('Admin')
def user_delete():
    id = request.args.get('id')
    if tesla_db.users.user_delete(id) is True:
        flash('Data deleted', 'success')
    else:
        flash('Data not deleted', 'error')


    return redirect(url_for('users.index'))

@users.route('/user_addedit', methods=['GET', 'POST'])
@login_required
@roles_required('Admin')
def user_addedit(id=0):
    id = int(request.args.get('id'))
    user_obj = tesla_db.users.get_user(id)

    form = UserForm(obj=user_obj)

    has_errors = True
    if form.validate_on_submit():
        tesla_db.users.user_addedit(id, form)
        flash('Data saved', 'success')
        return redirect(url_for('users.index'))
    else:
        return render_template('user_addedit.html', form=form, has_errors=has_errors, id=id)


@users.route('/roles', methods=['GET'])
@login_required
@roles_required('Admin')
def roles():
    return render_template('roles.html', page = 'users.roles')

tesla_admin/blueprints/users/templates/index.html
{% extends "layout.html" %}
{% block title %}{{ _('User Management')}}{% endblock %}
{% block header_css %}
    <!--
  ~ TeSLA Admin
  ~ Copyright (C) 2019 Universitat Oberta de Catalunya
  ~
  ~ This program is free software: you can redistribute it and/or modify
  ~ it under the terms of the GNU Affero General Public License as published by
  ~ the Free Software Foundation, either version 3 of the License, or
  ~ (at your option) any later version.
  ~
  ~ This program is distributed in the hope that it will be useful,
  ~ but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  ~ GNU Affero General Public License for more details.
  ~
  ~ You should have received a copy of the GNU Affero General Public License
  ~ along with this program.  If not, see <http://www.gnu.org/licenses/>.
  -->

<link rel="stylesheet" href="{{ url_for('static', filename='vendor/bootstrap-table/bootstrap-table.min.css') }}">
{% endblock %}

{% block sections %}
    <section class="dashboard-counts no-padding-bottom">
        <div class="row bg-white has-shadow">
            {% include "items/dashboard_count_item.html" %}
            <div class="col-4 col-xl-9 col-sm-6">
                <div class="text-right" style="margin-top:20px;">
                    <button type="button" data-entity-id="0" class="btn btn-xs btn-success btn-addedit"><i class="fa fa-plus"></i> {{ _('New user') }}</button>
                </div>
            </div>

        </div>
    </section>
    <section class="dashboard-counts no-padding-bottom">
        <div class="row bg-white has-shadow">
            <table class="table table-striped table-hover" id="table" data-toggle="table" data-url="{{ url_for('users.list_ajax') }}" data-pagination="true" data-search="true" data-side-pagination="server" data-page-list="[10, 25, 50, 100]">
                <thead>
                <tr>
                    <th data-field="id" data-sortable="true">#</th>
                    <th data-field="email" data-align="left" data-sortable="true">{{ _('Email') }}</th>
                    <th data-field="username" data-align="left" data-sortable="true">{{_('Username') }}</th>
                    <th data-field="active" data-formatter="active_format" data-sortable="true">{{ _('Active') }}</th>
                    <th data-field="actions" data-formatter="actions_format">{{ _('Actions') }}</th>
                </tr>
                </thead>
            </table>
        </div>
    </section>

    <div class="modal" tabindex="-1" role="dialog" id="entity_delete">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">{{ _('Delete user') }}</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>{{ _('Are you sure?') }}</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">{{ _('Close') }}</button>
                    <a id="button_entity_delete" href="#" class="btn btn-danger">{{ _('Save changes') }}</a>
                </div>
            </div>
        </div>
    </div>
    <div class="modal" tabindex="-1" role="dialog" id="entity_addedit">
        <div class="modal-dialog">
            <div class="modal-content">

            </div>
        </div>
    </div>
{% endblock %}
{% block body_scripts %}
    <script src="{{ url_for('static', filename='vendor/bootstrap-table/bootstrap-table.min.js') }}"></script>
    <script src="{{ url_for('static', filename='vendor/bootstrap-table/locale/bootstrap-table-en-US.js') }}"></script>
    <script src="{{ url_for('users.static', filename='js/user_list.js')}}"></script>
{% endblock %}

tesla_admin/blueprints/users/templates/roles.html
{% extends "layout.html" %}
{% block title %}{{ _('Roles Management')}}{% endblock %}
{% block sections %}

{% endblock %}
{% block body_scripts %}
{% endblock <!--
  ~ TeSLA Admin
  ~ Copyright (C) 2019 Universitat Oberta de Catalunya
  ~
  ~ This program is free software: you can redistribute it and/or modify
  ~ it under the terms of the GNU Affero General Public License as published by
  ~ the Free Software Foundation, either version 3 of the License, or
  ~ (at your option) any later version.
  ~
  ~ This program is distributed in the hope that it will be useful,
  ~ but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  ~ GNU Affero General Public License for more details.
  ~
  ~ You should have received a copy of the GNU Affero General Public License
  ~ along with this program.  If not, see <http://www.gnu.org/licenses/>.
  -->

%}

tesla_admin/blueprints/users/templates/user_addedit.html
<!--
  ~ TeSLA Admin
  ~ Copyright (C) 2019 Universitat Oberta de Catalunya
  ~
  ~ This program is free software: you can redistribute it and/or modify
  ~ it under the terms of the GNU Affero General Public License as published by
  ~ the Free Software Foundation, either version 3 of the License, or
  ~ (at your option) any later version.
  ~
  ~ This program is distributed in the hope that it will be useful,
  ~ but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  ~ GNU Affero General Public License for more details.
  ~
  ~ You should have received a copy of the GNU Affero General Public License
  ~ along with this program.  If not, see <http://www.gnu.org/licenses/>.
  -->

<form id="form_addedit" method="post" action="{{ url_for('users.user_addedit', id=id) }}">
    <div class="modal-header">
        <h5 class="modal-title">{% if id == 0 %}{{ _('New user') }}{% else %}{{ _('Edit user') }}{% endif %}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body">
        {% for field in form.errors %}
            {% for error in form.errors[field] %}
                <div class="alert alert-error">
                    <strong>Error!</strong> {{error}}
                </div>
            {% endfor %}
        {% endfor %}

        {{ form.hidden_tag() }}
        <div class="form-group">
            <label class="form-control-label">{{ form.username.label }}</label>
            {% set class_val = 'form-control is-invalid' if form.username.errors else 'form-control' %}
            {{ form.username(class_=class_val) }}
            {% for error in form.username.errors %}
                <div class="invalid-feedback">{{ error }}</div>
            {% endfor %}
        </div>
        <div class="form-group">
            <label class="form-control-label">{{ form.password.label }}</label>
            {% set class_val = 'form-control is-invalid' if form.password.errors else 'form-control' %}
            {{ form.password(class_=class_val) }}
            {% for error in form.password.errors %}
                <div class="invalid-feedback">{{ error }}</div>
            {% endfor %}
        </div>
        <div class="form-group">
            <label class="form-control-label">{{ form.repeat_password.label }}</label>
            {% set class_val = 'form-control is-invalid' if form.repeat_password.errors else 'form-control' %}
            {{ form.repeat_password(class_=class_val) }}
            {% for error in form.repeat_password.errors %}
                <div class="invalid-feedback">{{ error }}</div>
            {% endfor %}
        </div>
        <div class="form-group">
            <label class="form-control-label">{{ form.email.label }}</label>
            {% set class_val = 'form-control is-invalid' if form.email.errors else 'form-control' %}
            {{ form.email(class_=class_val) }}
            {% for error in form.email.errors %}
                <div class="invalid-feedback">{{ error }}</div>
            {% endfor %}
        </div>
        <div class="form-group">
            <label class="form-control-label">{{ form.active.label }}</label>
            {% set class_val = 'form-control is-invalid' if form.active.errors else 'form-control' %}
            {{ form.active(class_="checkbox-template") }}
            {% for error in form.active.errors %}
                <div class="invalid-feedback">{{ error }}</div>
            {% endfor %}
        </div>
        <div class="form-group">
            <label class="form-control-label">{{ form.roles.label }}</label>
            <div class="clearfix"></div>
            {% set class_val = 'form-control is-invalid' if form.roles.errors else 'form-control' %}
            {{ form.roles(class_="select2") }}
            {% for error in form.roles.errors %}
                <div class="invalid-feedback">{{ error }}</div>
            {% endfor %}
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-success btn-submit">Save</button>
    </div>
</form>
<script>

    $(".select2").select2({
        width: '100%'
    });

    $("form#form_addedit").validate({
        rules: {
            repeat_password: {
                equalTo: "#password"
            }
        }
    });

    $(".btn-submit").click(function(){
        if ($("form#form_addedit").valid()) {
            $("form#form_addedit").submit();
        }
    });

</script>