tesla_admin/blueprints/data/forms.py
#  TeSLA Admin
#  Copyright (C) 2019 Universitat Oberta de Catalunya
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
#
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

from flask_wtf import FlaskForm
from flask_wtf.form import _Auto
from flask_babel import gettext
from wtforms import StringField, BooleanField, SubmitField, SelectField, HiddenField, IntegerField, widgets, validators, ValidationError
from wtforms.fields.html5 import DateField

from tesla_admin import tesla_db

def unique_code_check(form, field):
    code = form.code.data
    id = form.id.data
    if code is None or len(code) == 0:
        raise ValidationError('Code must be provided')

    course = tesla_db.courses.get_course_by_code(code)
    if course is not None and course.id != int(id):
        raise ValidationError('Course code must be unique. This code is already used by another course.')


def get_vles():
    _vles = []
    vle_list = tesla_db.config.get_configured_vles()
    if vle_list is not None:
        _vles = [(str(vle.id), vle.name) for vle in vle_list]
    return _vles


def get_top_courses():
    _courses = [('-1' , '')]
    course_list = tesla_db.courses.get_active_top_courses()
    if course_list is not None:
        _courses = _courses + [(str(c.id), '[{}] - {}'.format(c.code, c.description)) for c in course_list]
    return _courses


def get_all_courses():
    _courses = [('-1' , '')]
    course_list = tesla_db.courses.get_active_courses()
    if course_list is not None:
        _courses = _courses + [(str(c.id), '[{}] - {}'.format(c.code, c.description)) for c in course_list]
    return _courses


class CourseForm(FlaskForm):

    def __init__(self, formdata=_Auto, **kwargs):
        super().__init__(formdata, **kwargs)
        self.update_dynamic_choices()


    id = IntegerField(widget=widgets.HiddenInput())
    #parent = SelectField(gettext('Parent Course'), choices=get_top_courses(), validators=(validators.Optional(),))
    parent = SelectField(gettext('Parent Course'), choices=get_all_courses(), validators=(validators.Optional(),))
    code = StringField(gettext('Code'), validators=[validators.DataRequired(), unique_code_check], render_kw={"placeholder": gettext('Course code')})
    description = StringField(gettext('Description'), validators=[validators.DataRequired()],
                              render_kw={"placeholder": gettext('Course description')})
    start = DateField('Start', format='%Y-%m-%d', validators=(validators.Optional(),))
    end = DateField('End', format='%Y-%m-%d', validators=(validators.Optional(),))
    vle_id = SelectField(gettext('VLE to connect'), choices=get_vles(), validators=(validators.Optional(),))
    vle_course_id = StringField(gettext('Course to connect'))
    submit = SubmitField(gettext('Save'))
    synchronize_vle = SubmitField(gettext('Synchronize with VLE'), default=None)
    delete = SubmitField(gettext('Delete'), default=None)

    def update_dynamic_choices(self):
        #self.parent.choices=get_top_courses()
        self.parent.choices = get_all_courses()
        self.vle_id.choices=get_vles()

tesla_admin/blueprints/data/__init__.py
#  TeSLA Admin
#  Copyright (C) 2019 Universitat Oberta de Catalunya
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
#
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

tesla_admin/blueprints/data/routes.py
#  TeSLA Admin
#  Copyright (C) 2019 Universitat Oberta de Catalunya
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
#
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

from flask import Blueprint, jsonify, url_for, render_template, request, redirect
from flask_security import roles_required, login_required, current_user, roles_accepted
from tesla_admin.decorators import certificate_required
from tesla_admin import logger, tesla_db
from tesla_admin.helpers import api_response
from tesla_admin.errors import TESLA_API_STATUS_CODE
from .forms import CourseForm
from tesla_models import models
from tesla_models.constants import TESLA_MESSAGE_TYPE, TESLA_REQUEST_STATUS
from tesla_admin import tasks
from flask_babelex import gettext

data = Blueprint('data', __name__, template_folder='templates', static_folder='static')


@data.route('/learner', methods=['GET'])
@login_required
@roles_required('Admin')
def learner():
    return render_template('learner.html', page= 'data.learner')


@data.route('/activity', methods=['GET'])
@login_required
@roles_required('Admin')
def activity():
    return render_template('activity.html', page= 'data.activity')


@data.route('/course', methods=['GET', 'POST'])
@login_required
@roles_required('Admin')
def course():
    form = CourseForm()
    has_errors = True
    if form.validate_on_submit():
        parent_id = form.data.get('parent')
        if parent_id == 'None':
            parent_id = None
        if parent_id is not None:
            parent_id = int(parent_id)
            if parent_id < 0:
                parent_id = None
        if form.data.get('submit') or form.data.get('synchronize_vle'):
            if form.data["id"] < 0:
                new_course = tesla_db.courses.create_course(code=form.data.get('code'), description=form.data.get('description'),
                                            start=form.data.get('start'), end=form.data.get('end'),
                                            vle_id=form.data.get('vle_id'), vle_course_id=form.data.get('vle_course_id'),
                                            parent_id=parent_id)
                form.id.data = new_course.id
                form.id.raw_data = [str(new_course.id)]
            else:
                if parent_id == form.data.get('id'):
                    parent_id = None
                tesla_db.courses.update_course(id=form.data.get('id'), code=form.data.get('code'),
                                               description=form.data.get('description'),
                                               start=form.data.get('start'), end=form.data.get('end'),
                                               vle_id=form.data.get('vle_id'),
                                               vle_course_id=form.data.get('vle_course_id'),
                                               parent_id=parent_id)
            has_errors = False

        if form.data.get('delete'):
            if tesla_db.courses.delete_course(form.data["id"]):
                return redirect(url_for('data.course'))

        if form.data.get('synchronize_vle'):
            course_to_sync = tesla_db.courses.get_child_courses_with_synch_data(int(form.id.data))

            for c in course_to_sync:
                if c.vle_course_id == '':
                    continue
                # Create a new task
                new_task = tesla_db.tasks.create_task(type="IMPORT_VLE_DATA", user_id=current_user.id)
                tasks.import_course_data.apply_async([new_task.id, c.id], priority=5)
                # Create a message to the user
                tesla_db.users.create_message(user_id=current_user.id, type=TESLA_MESSAGE_TYPE.TASK_CREATED,
                                              subject=gettext('New task created'), content=gettext(
                        "A new task to import all data from the course %(value)s has been created. This can take several hours depending on the system load. You will be notified.",
                                              value=c.description))

    if request.method == "GET":
        has_errors = False

    courses = tesla_db.courses.get_active_courses()
    form.update_dynamic_choices()

    return render_template('course.html', page='data.course', form=form, courses=courses, has_errors=has_errors)


@data.route('/course/<int:id>', methods=['GET'])
@login_required
@roles_required('Admin')
def get_course_data(id):
    course = tesla_db.courses.get_course(id)
    if course is None:
        return api_response(TESLA_API_STATUS_CODE.REQUEST_NOT_FOUND, http_code=404)

    parent_id = -1
    if course.parent_id is not None:
        parent_id = course.parent_id

    return api_response(TESLA_API_STATUS_CODE.SUCCESS, {'id': course.id, 'description': course.description,
                                                        'code': course.code, 'start': course.start, 'end': course.end,
                                                        'vle_id': course.vle_id, 'vle_course_id': course.vle_course_id,
                                                        'parent_id': parent_id})


@data.route('/course/<int:id>/activities', methods=['GET'])
@login_required
@roles_required('Admin')
def list_selected_activities_ajax(id):
    q = request.args.get('search')
    limit = request.args.get('limit')
    offset = request.args.get('offset')
    sort = request.args.get('sort')
    order = request.args.get('order')

    list_activities_data = tesla_db.courses.get_activities(course_id=id, q=q, limit=limit,
                                                                     offset=offset, order=order, sort=sort)
    total_activities = tesla_db.courses.count_activities(course_id=id, q=q)

    activities_data = models.courses_schema.dump(list_activities_data)

    return_data = {
        'total': total_activities,
        'rows': activities_data[0]
    }

    return jsonify(return_data), 200


@data.route('/course/<int:id>/available_activities', methods=['GET'])
@login_required
@roles_required('Admin')
def list_available_activities_ajax(id):
    q = request.args.get('search')
    limit = request.args.get('limit')
    offset = request.args.get('offset')
    sort = request.args.get('sort')
    order = request.args.get('order')

    list_activities_data = tesla_db.courses.get_available_activities(course_id=id, q=q, limit=limit, offset=offset,
                                                                     order=order, sort=sort)
    total_activities = tesla_db.courses.count_available_activities(course_id=id, q=q)

    activities_data = models.courses_schema.dump(list_activities_data)

    return_data = {
        'total': total_activities,
        'rows': activities_data[0]
    }

    return jsonify(return_data), 200


@data.route('/course/<int:course_id>/activity/<int:activity_id>', methods=['DELETE', 'POST'])
@login_required
@roles_required('Admin')
def course_activity(course_id, activity_id):

    if request.method == "DELETE":
        tesla_db.courses.delete_activity(course_id, activity_id)

    if request.method == "POST":
        tesla_db.courses.add_activity(course_id, activity_id)

    return api_response(TESLA_API_STATUS_CODE.SUCCESS)


@data.route('/learner/data/<string:tesla_id>', methods=["GET"])
@login_required
@roles_accepted('Admin', 'Statistics')
def get_learner_data_summary(tesla_id):

    summary = {
        'tesla_id': tesla_id,
        'courses': tesla_db.learners.count_learner_courses(tesla_id),
        'activities': tesla_db.learners.count_learner_activities(tesla_id)
    }

    return api_response(TESLA_API_STATUS_CODE.SUCCESS, summary)


@data.route('/learner/<string:tesla_id>', methods=["DELETE"])
@login_required
@roles_required('Admin')
def delete_learner(tesla_id):
    # Create a new task
    new_task = tesla_db.tasks.create_task(type="DELETE_LEARNER_DATA", user_id=current_user.id)
    tasks.delete_learner_data.apply_async([new_task.id, tesla_id], priority=5)
    # Create a message to the user
    tesla_db.users.create_message(user_id=current_user.id, type=TESLA_MESSAGE_TYPE.TASK_CREATED,
                                  subject=gettext('New task created'), content=gettext(
            "A new task to delete all data from user %(value)s has been created. This can take several hours depending on the system load. You will be notified.",
            value=tesla_id))

    return api_response(TESLA_API_STATUS_CODE.SUCCESS)


@data.route('/activity/<string:activity_id>', methods=["DELETE"])
@login_required
@roles_required('Admin')
def delete_activity(activity_id):
    # Create a new task
    new_task = tesla_db.tasks.create_task(type="DELETE_ACTIVITY_DATA", user_id=current_user.id)
    tasks.delete_activity_data.apply_async([new_task.id, activity_id], priority=5)
    # Create a message to the user
    tesla_db.users.create_message(user_id=current_user.id, type=TESLA_MESSAGE_TYPE.TASK_CREATED,
                                  subject=gettext('New task created'), content=gettext(
            "A new task to delete all data for activity %(value)s has been created. This can take several hours depending on the system load. You will be notified.",
            value=activity_id))

    return api_response(TESLA_API_STATUS_CODE.SUCCESS)


@data.route('/activities', methods=['GET'])
@login_required
@roles_required('Admin')
def list_activities_ajax():
    q = request.args.get('search')
    limit = request.args.get('limit')

tesla_admin/blueprints/data/templates/activity.html
{% extends "layout.html" %}
{% block title %}{{ _('Activity Data Management') }}{% endblock %}
{% block sections %}
    <!--
  ~ TeSLA Admin
  ~ Copyright (C) 2019 Universitat Oberta de Catalunya
  ~
  ~ This program is free software: you can redistribute it and/or modify
  ~ it under the terms of the GNU Affero General Public License as published by
  ~ the Free Software Foundation, either version 3 of the License, or
  ~ (at your option) any later version.
  ~
  ~ This program is distributed in the hope that it will be useful,
  ~ but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  ~ GNU Affero General Public License for more details.
  ~
  ~ You should have received a copy of the GNU Affero General Public License
  ~ along with this program.  If not, see <http://www.gnu.org/licenses/>.
  -->

<div class="col-lg-12">
        <div class="card">
            <div class="card-header d-flex align-items-center">
                <h3 class="h4">{{ _("Delete Activity Data") }}</h3>
            </div>
            <div class="card-body d-flex justify-content-center">
                <table class="table table-striped table-hover"
                       id="table_selected_activities"
                       data-toggle="table"
                       data-pagination="true"
                       data-url="{{ url_for('data.list_activities_ajax') }}"
                       data-search="true"
                       data-side-pagination="server"
                       data-page-list="[10, 25, 50, 100]">
                    <thead>
                        <tr>
                            <th data-field="id" data-sortable="true">#</th>
                            <th data-field="vle_id" data-align="left" data-sortable="true">{{ _('VLE') }}</th>
                            <th data-field="activity_type" data-align="left" data-sortable="true">{{_('Type') }}</th>
                            <th data-field="activity_id" data-align="left" data-sortable="true">{{ _('Id') }}</th>
                            <th data-field="description" data-align="left" data-sortable="true">{{ _('Description') }}</th>
                            <th data-field="actions" data-formatter="actions_format_selected"></th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
{% endblock %}
{% block body_scripts %}
    <script src="{{ url_for('static', filename='vendor/bootstrap-table/bootstrap-table.min.js') }}"></script>
    <script src="{{ url_for('static', filename='vendor/bootstrap-table/locale/bootstrap-table-en-US.js') }}"></script>
    <script src="{{ url_for('data.static', filename='js/activities.js') }}"></script>
{% endblock %}

tesla_admin/blueprints/data/templates/course.html
{% extends "layout.html" %}
{% block title %}{{ _('Course Management') }}{% endblock %}
{% block header_css %}
    <!--
  ~ TeSLA Admin
  ~ Copyright (C) 2019 Universitat Oberta de Catalunya
  ~
  ~ This program is free software: you can redistribute it and/or modify
  ~ it under the terms of the GNU Affero General Public License as published by
  ~ the Free Software Foundation, either version 3 of the License, or
  ~ (at your option) any later version.
  ~
  ~ This program is distributed in the hope that it will be useful,
  ~ but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  ~ GNU Affero General Public License for more details.
  ~
  ~ You should have received a copy of the GNU Affero General Public License
  ~ along with this program.  If not, see <http://www.gnu.org/licenses/>.
  -->

<link rel="stylesheet" href="{{ url_for('static', filename='vendor/bootstrap-table/bootstrap-table.min.css') }}">
{% endblock %}
{% block sections %}
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header d-flex align-items-center">
                <h3 class="h4">{{ _("Course") }}</h3>
            </div>
            <div class="card-body d-flex justify-content-center">
                <div class="course-search" style="width: 100%;">
                    <form class="form">
                        <div class="form-group">
                            <label class="col-sm-3 form-control-label">{{ _('Select one course to edit') }}</label>
                            <div class="col-lg-6 select">
                                <div class="input-group">
                                    <select id="courses" name="course" class="form-control">
                                        <option value="-1"></option>
                                        {% for c in courses %}
                                        <option value="{{c.id}}"><b>[{{c.code}}]</b> - {{c.description}}</option>
                                        {% endfor %}
                                    </select>
                                    <div class="input-group-prepend">
                                        <button type="button" class="btn btn-primary new_course">{{ _("New") }}</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-12 course-details" {% if has_errors == False %}style="display: none;"{% endif %}>
        <div class="card">
            <div class="card-header d-flex align-items-center">
                <h3 class="h4">{{ _("Details") }}</h3>
            </div>
            <div class="card-body d-flex justify-content-center">
                <div class="pt-5 pb-5 course-form-loading" style="display: none;">
                    <div class="sk-circle course-form-loading" style="display: none;">
                        <div class="sk-circle1 sk-child course-form-loading" style="display: none;"></div>
                        <div class="sk-circle2 sk-child course-form-loading" style="display: none;"></div>
                        <div class="sk-circle3 sk-child course-form-loading" style="display: none;"></div>
                        <div class="sk-circle4 sk-child course-form-loading" style="display: none;"></div>
                        <div class="sk-circle5 sk-child course-form-loading" style="display: none;"></div>
                        <div class="sk-circle6 sk-child course-form-loading" style="display: none;"></div>
                        <div class="sk-circle7 sk-child course-form-loading" style="display: none;"></div>
                        <div class="sk-circle8 sk-child course-form-loading" style="display: none;"></div>
                        <div class="sk-circle9 sk-child course-form-loading" style="display: none;"></div>
                        <div class="sk-circle10 sk-child course-form-loading" style="display: none;"></div>
                        <div class="sk-circle11 sk-child course-form-loading" style="display: none;"></div>
                        <div class="sk-circle12 sk-child course-form-loading" style="display: none;"></div>
                    </div>
                </div>
                <form id="form_course" class="form course-form" method="post" style="width: 100%; {% if has_errors == False %}display: none;{% endif %}">
                    {{ form.hidden_tag() }}
                    <div class="form-group">
                        <label class="form-control-label">{{ form.parent.label }}</label>
                        {{ form.parent(class_='form-control') }}
                    </div>
                    <div class="form-group">
                        <label class="form-control-label">{{ form.code.label }}</label>
                        {% set class_val = 'form-control is-invalid' if form.code.errors else 'form-control' %}
                        {{ form.code(class_=class_val) }}
                        {% for error in form.code.errors %}
                            <div class="invalid-feedback">{{ error }}</div>
                        {% endfor %}
                    </div>
                    <div class="form-group">
                        <label class="form-control-label">{{ form.description.label }}</label>
                        {% set class_val = 'form-control is-invalid' if form.description.errors else 'form-control' %}
                        {{ form.description(class_=class_val) }}
                        {% for error in form.description.errors %}
                            <div class="invalid-feedback">{{ error }}</div>
                        {% endfor %}
                    </div>
                    <div class="form-group row">
                        <div class="col-sm-6">
                        <label class="form-control-label">{{ form.start.label }}</label>
                            {% set class_val = 'form-control datepicker is-invalid' if form.start.errors else 'form-control datepicker' %}
                            {{ form.start(class_=class_val) }}
                            {% for error in form.start.errors %}
                                <div class="invalid-feedback">{{ error }}</div>
                            {% endfor %}
                        </div>
                        <div class="col-sm-6">
                        <label class="form-control-label">{{ form.end.label }}</label>
                            {% set class_val = 'form-control datepicker is-invalid' if form.end.errors else 'form-control datepicker' %}
                            {{ form.end(class_=class_val) }}
                            {% for error in form.end.errors %}
                                <div class="invalid-feedback">{{ error }}</div>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-sm-6">
                        <label class="form-control-label">{{ form.vle_id.label }}</label>
                            {% set class_val = 'form-control select is-invalid' if form.vle_id.errors else 'form-control select' %}
                            {{ form.vle_id(class_=class_val) }}
                            {% for error in form.vle_id.errors %}
                                <div class="invalid-feedback">{{ error }}</div>
                            {% endfor %}
                        </div>
                        <div class="col-sm-6">
                        <label class="form-control-label">{{ form.vle_course_id.label }}</label>
                            {% set class_val = 'form-control select is-invalid' if form.vle_course_id.errors else 'form-control select' %}
                            {{ form.vle_course_id(class_=class_val) }}
                            {% for error in form.vle_course_id.errors %}
                                <div class="invalid-feedback">{{ error }}</div>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="form-group">
                        {{ form.submit(class_="btn btn-primary")}}
                        {{ form.synchronize_vle(class_="btn btn-success float-right")}}
                        {{ form.delete(class_="btn btn-danger float-right")}}
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="col-lg-12 course-activities" {% if has_errors == False %}style="display: none;"{% endif %}>
        <div class="card">
            <div class="card-header d-flex align-items-center">
                <h3 class="h4">{{ _("Activities") }}</h3>
            </div>
            <div class="card-body d-flex justify-content-center">
                <div class="row col-lg-12">
                    <div class="col-lg-6">
                        <h4>{{ _('Available') }}</h4>
                        <table class="table table-striped table-hover"
                               id="table_available_activities"
                               data-toggle="table"
                               data-pagination="true"
                               data-search="true"
                               data-side-pagination="server"
                               data-page-list="[10, 25, 50, 100]">
                            <thead>
                                <tr>
                                    <th data-field="id" data-sortable="true">#</th>
                                    <th data-field="vle_id" data-align="left" data-sortable="true">{{ _('VLE') }}</th>
                                    <th data-field="activity_type" data-align="left" data-sortable="true">{{_('Type') }}</th>
                                    <th data-field="activity_id" data-align="left" data-sortable="true">{{ _('Id') }}</th>
                                    <th data-field="description" data-align="left" data-sortable="true">{{ _('Description') }}</th>
                                    <th data-field="actions" data-formatter="actions_format_available"></th>
                                </tr>
                            </thead>
                        </table>
                    </div>
                    <div class="col-lg-6">
                        <h4>{{ _('Selected') }}</h4>
                        <table class="table table-striped table-hover"
                               id="table_selected_activities"
                               data-toggle="table"
                               data-pagination="true"
                               data-search="true"
                               data-side-pagination="server"
                               data-page-list="[10, 25, 50, 100]">
                            <thead>
                                <tr>
                                    <th data-field="id" data-sortable="true">#</th>
                                    <th data-field="vle_id" data-align="left" data-sortable="true">{{ _('VLE') }}</th>
                                    <th data-field="activity_type" data-align="left" data-sortable="true">{{_('Type') }}</th>
                                    <th data-field="activity_id" data-align="left" data-sortable="true">{{ _('Id') }}</th>
                                    <th data-field="description" data-align="left" data-sortable="true">{{ _('Description') }}</th>
                                    <th data-field="actions" data-formatter="actions_format_selected"></th>
                                </tr>
                            </thead>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block body_scripts %}
    <script src="{{ url_for('static', filename='vendor/bootstrap-table/bootstrap-table.min.js') }}"></script>
    <script src="{{ url_for('static', filename='vendor/bootstrap-table/locale/bootstrap-table-en-US.js') }}"></script>
    <script src="{{ url_for('data.static', filename='js/courses.js') }}"></script>
{% endblock %}

tesla_admin/blueprints/data/templates/learner.html
{% extends "layout.html" %}
{% block title %}{{ _('Data Management') }}{% endblock %}
{% block sections %}
    {% include "sections/find_learner.html" %}
    {% include "sections/data_learner_data.html" %}
{% endblock %}
{% block body_scripts %}
    <!--
  ~ TeSLA Admin
  ~ Copyright (C) 2019 Universitat Oberta de Catalunya
  ~
  ~ This program is free software: you can redistribute it and/or modify
  ~ it under the terms of the GNU Affero General Public License as published by
  ~ the Free Software Foundation, either version 3 of the License, or
  ~ (at your option) any later version.
  ~
  ~ This program is distributed in the hope that it will be useful,
  ~ but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  ~ GNU Affero General Public License for more details.
  ~
  ~ You should have received a copy of the GNU Affero General Public License
  ~ along with this program.  If not, see <http://www.gnu.org/licenses/>.
  -->

<script src="{{ url_for('static', filename='vendor/bootstrap-table/bootstrap-table.min.js') }}"></script>
    <script src="{{ url_for('static', filename='vendor/bootstrap-table/locale/bootstrap-table-en-US.js') }}"></script>
    <script src="{{ url_for('static', filename='vendor/jquery-sparkline/jquery.sparkline.min.js') }}"></script>
    <script src="{{ url_for('data.static', filename='js/learners.js') }}"></script>
{% endblock %}